wandb_version: 1

kernel_size:
  desc: null
  value: 27
reg:
  desc: null
  value: 1.0e-05
dropout:
  desc: null
  value: 0.6
start_filters:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.0001
input_size:
  desc: null
  value: 1024
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716482473
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      - 61
      - 62
      4: 3.9.19
      5: 0.17.0
      8:
      - 1
      - 5
      10:
      - 9
      13: darwin-arm64
